[package]
name = "c2patool"
default-run = "c2patool"

# Please do not manually edit `version`. Version updates will be generated
# automatically when c2patool is published. Remember to use (MINOR) or (MAJOR)
# tags in the PR title to trigger non-patch updates as needed.
version = "0.9.0"

description = "Tool for displaying and creating C2PA manifests."
authors = [
	"Gavin Peacock <gpeacock@adobe.com>",
	"Maurice Fisher <mfisher@adobe.com>",
]
license = "MIT OR Apache-2.0"
documentation = "https://opensource.contentauthenticity.org/docs/c2patool"
readme = "README.md"
keywords = ["c2pa", "xmp", "metadata"]
edition = "2018"
rust-version = "1.61.0"
homepage = "https://contentauthenticity.org"
repository = "https://github.com/contentauth/c2patool"

[dependencies]
anyhow = "1.0"
c2pa = { version = "0.32.0", features = [
	"fetch_remote_manifests",
	"file_io",
	"add_thumbnails",
	"pdf",
] }
clap = { version = "4.5.2", features = ["derive", "env"] }
env_logger = "0.9"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "3.3"
pem = "3.0.3"
openssl = { version = "0.10.61", features = ["vendored"] }
reqwest = { version = "0.12.4", features = ["blocking"] }
url = "2.5.0"

[dev-dependencies]
assert_cmd = "2.0.14"
httpmock = "0.7.0"
predicates = "2.1"
mockall = "0.12.1"

[package.metadata.binstall]
bin = "c2patool"

[profile.release]
strip = true  # Automatically strip symbols from the binary. 
opt-level = 3
lto = "thin"  # Link time optimization.

[[bin]]
name = "signer-path-fail"

[[bin]]
name = "signer-path-no-stdout"

[[bin]]
name = "signer-path-success"
