[package]
name = "c2patool"
default-run = "c2patool"

# Please do not manually edit `version`. Version updates will be generated
# automatically when c2patool is published. Remember to use (MINOR) or (MAJOR)
# tags in the PR title to trigger non-patch updates as needed.
version = "0.9.3"

description = "Tool for displaying and creating C2PA manifests."
authors = [
	"Gavin Peacock <gpeacock@adobe.com>",
	"Maurice Fisher <mfisher@adobe.com>",
]
license = "MIT OR Apache-2.0"
documentation = "https://opensource.contentauthenticity.org/docs/c2patool"
readme = "README.md"
keywords = ["c2pa", "xmp", "metadata"]
edition = "2018"
rust-version = "1.61.0"
homepage = "https://contentauthenticity.org"
repository = "https://github.com/contentauth/c2patool"

[dependencies]
anyhow = "1.0"
c2pa = { git = "https://github.com/contentauth/c2pa-rs.git", features = [
	"fetch_remote_manifests",
	"file_io",
	"add_thumbnails",
	"pdf",
	"unstable_api",
] }
clap = { version = "4.5.2", features = ["derive", "env"] }
env_logger = "0.9"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
pem = "3.0.2"
openssl = { version = "0.10.61", features = ["vendored"] }
reqwest = { version = "0.12.4", features = ["blocking"] }
wild = "2.2.1"
termtree = "0.5.1"

[dev-dependencies]
tempfile = "3.3"
httpmock = "0.7.0"
mockall = "0.12.1"
insta = { version = "1.39.0", features = ["json", "redactions", "filters"] }
insta-cmd = "0.6.0"

[package.metadata.binstall]
# Use defaults

# https://insta.rs/docs/quickstart/
[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[profile.release]
strip = true  # Automatically strip symbols from the binary. 
opt-level = 3
lto = "thin"  # Link time optimization.
