# Enforce Tier 1A support tier.

# See tier-1b.yml for a more complete suite of tests.
# You can add the label "check-release" to any PR to invoke that
# larger set of tests.

# If you change the supported platforms in this workflow, please also
# update docs/support-tiers.md to match the changes you're making.

name: Tier 1A

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - v1_api
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  push:
    branches:
      - main
      - v1_api

jobs:
  get-features:
    name: Get features
    runs-on: ubuntu-latest
    outputs:
      rust-native-features: ${{ steps.get-features.outputs.rust-native-features }}
      openssl-features: ${{ steps.get-features.outputs.openssl-features }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Get all features
        id: get-features
        run: |
          FEATURES=$(cargo metadata --format-version=1 | jq -r '[.packages[] | select(.name=="c2pa") | .features | keys | map(select(. != "default")) | .[]] | unique | join(" ")')

          RUST_NATIVE_FEATURES=$(echo $FEATURES | sed 's/openssl//g')
          OPENSSL_FEATURES=$(echo $FEATURES | sed 's/rust_native_crypto//g')
          echo "rust-native-features=$RUST_NATIVE_FEATURES" >> "$GITHUB_OUTPUT"
          echo "openssl-features=$OPENSSL_FEATURES" >> "$GITHUB_OUTPUT"

  tests-cli:
    name: Unit tests (c2patool)
    needs: get-features
    if: |
      github.event_name != 'pull_request' ||
      github.event.pull_request.author_association == 'COLLABORATOR' ||
      github.event.pull_request.author_association == 'MEMBER' ||
      github.event.pull_request.user.login == 'dependabot[bot]' ||
      contains(github.event.pull_request.labels.*.name, 'safe to test')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        env:
          RUST_BACKTRACE: "1"
          FEATURES: ${{needs.get-features.outputs.openssl-features}}
        run: |
          cargo llvm-cov --bins --features "$FEATURES" --lcov --output-path lcov.info

      # Tokens aren't available for PRs originating from forks,
      # so we don't attempt to upload code coverage in that case.
      - name: Upload code coverage results
        if: |
          github.event_name != 'pull_request' ||
          github.event.pull_request.author_association == 'COLLABORATOR' ||
          github.event.pull_request.author_association == 'MEMBER' ||
          github.event.pull_request.user.login == 'dependabot[bot]'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          files: ./lcov-openssl.info,./lcov-rust_native_crypto.info
